# Generated by Django 3.2.4 on 2021-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionslist',
            name='complexity',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('COMPLICATED', 'COMPLICATED')], default='SIMPLE', max_length=20, verbose_name='Сложность'),
        ),
    ]
