# Generated by Django 3.1.4 on 2021-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_top',
            field=models.BooleanField(default=True, verbose_name='Is_top'),
        ),
    ]
