# Generated by Django 3.1.4 on 2020-12-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.CharField(max_length=150, verbose_name='Answer')),
                ('clarification', models.TextField(verbose_name='Clarification')),
            ],
            options={
                'verbose_name': 'QuestionsList',
                'verbose_name_plural': 'QuestionsList',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='subcategory',
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'managed': True, 'verbose_name': 'AnswerOption', 'verbose_name_plural': 'AnswerOptions'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'managed': True, 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'managed': True, 'verbose_name': 'Points', 'verbose_name_plural': 'Points'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'managed': True, 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='topplayer',
            options={'managed': True, 'verbose_name': 'TopPlayer', 'verbose_name_plural': 'TopPlayers'},
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='option',
            field=models.CharField(max_length=150, verbose_name='Option of answer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(max_length=150, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('ST', 'SENT'), ('CD', 'UNDER CONSIDERATION'), ('RJ', 'REJECT'), ('AC', 'ACCEPT'), ('FX', 'FIXED')], default='ST', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='points',
            name='commonPoints',
            field=models.PositiveIntegerField(default=0, verbose_name='Common quantity points'),
        ),
        migrations.AlterField(
            model_name='points',
            name='numberGames',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of games'),
        ),
        migrations.AlterField(
            model_name='points',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='nameSubcategory',
            field=models.CharField(max_length=150, verbose_name='Subcategory'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='questionslist',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.questionslist', verbose_name='QuestionsList'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.questionslist', verbose_name='QuestionsList'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
