# Generated by Django 3.1.4 on 2021-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0002_user_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_top',
        ),
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
