# Generated by Django 3.1.4 on 2021-01-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0003_auto_20210103_2122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answeroption',
            table='answerOptions',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='points',
            table='points',
        ),
        migrations.AlterModelTable(
            name='questionslist',
            table='questionsList',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
        migrations.AlterModelTable(
            name='topplayer',
            table='topPlayers',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
