# Generated by Django 3.1.4 on 2020-12-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0003_auto_20201211_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='option',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='first_option',
            field=models.CharField(default=None, max_length=150, verbose_name='First option'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='fourth_option',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fourth option'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='second_option',
            field=models.CharField(default=None, max_length=150, verbose_name='Second option'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='third_option',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Third option'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.questionslist', verbose_name='QuestionsList'),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='clarification',
            field=models.TextField(blank=True, null=True, verbose_name='Clarification'),
        ),
    ]
