# Generated by Django 3.1.4 on 2021-02-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0004_auto_20210105_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'managed': True, 'verbose_name': 'Варианты ответов', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'managed': True, 'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'managed': True, 'verbose_name': 'Баллы', 'verbose_name_plural': 'Баллы'},
        ),
        migrations.AlterModelOptions(
            name='questionslist',
            options={'managed': True, 'verbose_name': 'Список вопросов', 'verbose_name_plural': 'Список вопросов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'managed': True, 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='topplayer',
            options={'managed': True, 'verbose_name': 'Лучшие игроки', 'verbose_name_plural': 'Лучшие игроки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='first_option',
            field=models.CharField(max_length=150, verbose_name='Первый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='fourth_option',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Четвертый вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answerOptions', to='questionsAnswers.questionslist', verbose_name='Список вопросов'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='second_option',
            field=models.CharField(max_length=150, verbose_name='Второй вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='third_option',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Третий вариант ответа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(max_length=150, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questionsAnswers.news', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.questionslist', verbose_name='Список вопросов'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('UNDER CONSIDERATION', 'UNDER CONSIDERATION'), ('REJECT', 'REJECT'), ('ACCEPT', 'ACCEPT'), ('FIXED', 'FIXED')], default='SENT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='points',
            name='commonPoints',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее число баллов'),
        ),
        migrations.AlterField(
            model_name='points',
            name='numberGames',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество игр'),
        ),
        migrations.AlterField(
            model_name='points',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='answer',
            field=models.CharField(max_length=150, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='clarification',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='question',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsAnswers.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='nameSubcategory',
            field=models.CharField(max_length=150, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='topplayer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
