# Generated by Django 3.1.4 on 2020-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0004_auto_20201211_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='first_option',
            field=models.CharField(max_length=150, verbose_name='First option'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='second_option',
            field=models.CharField(max_length=150, verbose_name='Second option'),
        ),
    ]
