# Generated by Django 3.1.4 on 2020-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0005_auto_20201211_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('UNDER CONSIDERATION', 'UNDER CONSIDERATION'), ('REJECT', 'REJECT'), ('ACCEPT', 'ACCEPT'), ('FIXED', 'FIXED')], default='SENT', max_length=20, verbose_name='Status'),
        ),
    ]
