# Generated by Django 3.1.4 on 2020-12-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0009_auto_20201220_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topplayer',
            name='points',
        ),
    ]
