# Generated by Django 3.1.4 on 2020-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0011_auto_20201220_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
