# Generated by Django 3.1.4 on 2020-12-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0012_news_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
    ]
