# Generated by Django 3.1.4 on 2020-12-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsAnswers', '0013_auto_20201221_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answerOptions', to='questionsAnswers.questionslist', verbose_name='QuestionsList'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questionsAnswers.news', verbose_name='News'),
        ),
    ]
